openapi: 3.0.0
info:
  title: Your API
  description: API documentation for your application
  version: 1.0.0
paths:
  /api/groups:
    get:
      summary: Get a list of groups
      description: Retrieve a list of groups.
      responses:
        '200':
          description: A list of groups.
  /api/users:
    get:
      summary: Get a list of users
      description: Retrieve a list of users.
      responses:
        '200':
          description: A list of users.
  /api/auth/login:
    post:
      summary: Login
      description: Login to your account.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful.
  /api/auth/register:
    post:
      summary: Register
      description: Register a new account.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Registration successful.
