openapi: 3.0.0
info:
  title: Your API
  description: API documentation for your application
  version: 1.0.0
servers:
  - url: http://127.0.0.1:8000/api
tags:
  - name: Auth
  - name: Users
  - name: Groups
paths:
  /groups:
    get:
      tags:
        - Groups
      summary: Get a list of groups
      description: Retrieve a list of groups.
      responses:
        '200':
          description: A list of groups.
  /users:
    get:
      tags:
        - Users
      summary: Get a list of users
      description: Retrieve a list of users.
      responses:
        '200':
          description: A list of users.
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login
      description: Login to your account.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful.
  /auth/register:
    post:
      tags:
        - Auth
      summary: Register
      description: Register a new account.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Registration successful.
